### ISSUE TITLE
Left Join not working?

### ISSUE THREAD

**Issue by nszekeres** [edquant/edh7916#31] opened 2020-06-12 04:01 UTC
Not sure if this is just me... I did find issues confirmed on the internet.
My left_join appears to be working inconsistently... it worked in one instance, but not in the below. 
Any ideas? Ty.

### Data that I wish to join (x1txmtscor_m is a newly created variable):

```r
> df_q2
A tibble: 16,761 x 5
Groups:   x1famincome, x1region [52]
   stu_id x1region x1txmtscor x1famincome x1txmtscor_m
    <dbl>    <dbl>      <dbl>       <dbl>        <dbl>
 1  10001        2       59.4          10         55.5
 2  10002        1       47.7           3         49.9
 3  10003        4       64.2           6         51.8
 4  10004        3       49.3           5         52.7
 5  10005        3       62.6           9         56.5
 6  10006        3       58.1           5         52.7
 7  10007        1       49.5           4         52.2
 8  10008        1       54.6           7         55.0
 9  10009        3       53.2           4         50.8
10  10010        1       63.8           4         52.2
 ... with 16,751 more rows
```
### To this original dataframe (df):
```r
> df
 A tibble: 23,503 x 16
   stu_id x1sex x1race x1stdob x1txmtscor x1paredu x1hhnumber x1famincome
    <dbl> <dbl>  <dbl>   <dbl>      <dbl>    <dbl>      <dbl>       <dbl>
 1  10001     1      8  199502       59.4        5          3          10
 2  10002     2      8  199511       47.7        3          6           3
 3  10003     2      3  199506       64.2        7          3           6
 4  10004     2      8  199505       49.3        4          2           5
 5  10005     1      8  199505       62.6        4          4           9
 6  10006     2      8  199504       58.1        3          6           5
 7  10007     2      8  199409       49.5        2          2           4
 8  10008     1      8  199410       54.6        7          3           7
 9  10009     1      8  199501       53.2        2          3           4
10  10010     2      8  199503       63.8        3          4           4
 ... with 23,493 more rows, and 8 more variables: x1poverty185 <dbl>,
   x1ses <dbl>, x1stuedexpct <dbl>, x1paredexpct <dbl>, x1region <dbl>,
   x4hscompstat <dbl>, x4evratndclg <dbl>, x4hs2psmos <dbl>
```
### And this is the code with which I'm attempting to complete the task:
```r
df_q2_joined <- df
      df_q2_joined %>%
        left_join(df_q2, by = "stu_id") 
      _## I also tried "left_join(df_q2, by = "x1famincome", "x1region")" and it didn't join, either_
      df_q2_joined
```
*I tried different keys, "stud_id" AND "x1region", "x1famincome" - nothing is working. 
I also couldn't join other tables on other problems I attempted, so not sure what's going on.

**Comment by btskinner** [comment] 2020-06-12 15:26
First thing, I've edited your above post to include code fence blocks. You can see this if you click the three dots in the upper right of the comment box and then **Edit**. If you use these in the future, it will help separate your code from everything else, making it all easier to read.

For your question, I'm not totally clear what you are trying to do. Do you need all the extra variables in `df_q2` or just the new variable? If the later, part of the join issue might be that you end up with redundant columns at the end.

Looking at your last bit of code:

```r
df_q2_joined <- df
    df_q2_joined %>%
    left_join(df_q2, by = "stu_id") 
    ## I also tried "left_join(df_q2, by = "x1famincome", "x1region")" and it didn't join, either
df_q2_joined
```
You don't need the second `df_q2_joined` in your function chain. Just start with the data.frame on the left (`df`) then `%>%` to `left_join(df_q2, by = "stu_id")`. If `stu_id` is unique in each data.frame and you don't have redundant variables, you will probably get what you expect.

As a last note, if you are trying to join on more than one key (per your comment), be sure to surround the multiple keys with `c()`: `c("x1famincome", "x1region")`. That may not be what you need here, but for future reference.

**Comment by nszekeres** [comment] 2020-06-13 02:09
Thanks, Dr. Skinner - and wow. 

The 2nd ...df_q2_joined... was not the issue; I tried it both ways.

But what you mention, "if you don't have **redundant variables" is probably the issue. Can you explain that?** I thought that it would simply ignore redundant variables (especially if the columns contain identical values)... And in one case, I saw that the join managed the redundancy just the way a computer would handle a duplicate download of a file: by labeling it with a (2) etc. In one instance, when I tried the join, it brought in the two redundant variables with a (2) label, but it somehow skipped the new/unique variable I was interested in joining to the table... why is that??

This R lingo is funky. :( 
Thanks for the help!

**Comment by nszekeres** [comment] 2020-06-13 18:55
*Update: 
It joined and took the extra 2 variables and labeled them ".y"
I think my machine is just running slow, having trouble digesting the variables; or, I overwrote something when I was fiddling around. :(

**Comment by btskinner** [comment] 2020-06-14 13:46
@nszekeres: it seems that you've got it figured, but let me clarify from above. Here's a reproducible example (or [reprex](https://reprex.tidyverse.org)) that first shows a join that ends with redundant variables. After that, it shows two ways to prevent that from happening. Which of the two ways you use will depend on your underlying data frames or particular data analysis needs.

# Example

``` r
## load library
library(tidyverse)
```

``` r
## set up data frames
```

``` r

## state abbreviation, region, per capita income (1975)
df_1 <- tibble(stabbr = state.abb,
               region = state.region,
               income = state.x77[,2])

## state abbreviation, region, percent high school graduates (1970)
df_2 <- tibble(stabbr = state.abb,
               region = state.region,
               hsgrad = state.x77[,6])

## show
df_1
#> # A tibble: 50 x 3
#>    stabbr region    income
#>    <chr>  <fct>      <dbl>
#>  1 AL     South       3624
#>  2 AK     West        6315
#>  3 AZ     West        4530
#>  4 AR     South       3378
#>  5 CA     West        5114
#>  6 CO     West        4884
#>  7 CT     Northeast   5348
#>  8 DE     South       4809
#>  9 FL     South       4815
#> 10 GA     South       4091
#> # … with 40 more rows
df_2
#> # A tibble: 50 x 3
#>    stabbr region    hsgrad
#>    <chr>  <fct>      <dbl>
#>  1 AL     South       41.3
#>  2 AK     West        66.7
#>  3 AZ     West        58.1
#>  4 AR     South       39.9
#>  5 CA     West        62.6
#>  6 CO     West        63.9
#>  7 CT     Northeast   56  
#>  8 DE     South       54.6
#>  9 FL     South       52.6
#> 10 GA     South       40.6
#> # … with 40 more rows
```

``` r
## redundant columns
```

``` r

## join, but ignore the fact that region is in both
df_redundant_join <- df_1 %>%
    left_join(df_2, by = "stabbr")

## show and note region.x and region.y
df_redundant_join
#> # A tibble: 50 x 5
#>    stabbr region.x  income region.y  hsgrad
#>    <chr>  <fct>      <dbl> <fct>      <dbl>
#>  1 AL     South       3624 South       41.3
#>  2 AK     West        6315 West        66.7
#>  3 AZ     West        4530 West        58.1
#>  4 AR     South       3378 South       39.9
#>  5 CA     West        5114 West        62.6
#>  6 CO     West        4884 West        63.9
#>  7 CT     Northeast   5348 Northeast   56  
#>  8 DE     South       4809 South       54.6
#>  9 FL     South       4815 South       52.6
#> 10 GA     South       4091 South       40.6
#> # … with 40 more rows
```

``` r
## no redundant columns
```

``` r

## version 1: drop redundant column from one data frame before join
df_2_drop <- df_2 %>%
    select(-region)

df_drop_join <- df_1 %>%
    left_join(df_2_drop, by = "stabbr")

df_drop_join
#> # A tibble: 50 x 4
#>    stabbr region    income hsgrad
#>    <chr>  <fct>      <dbl>  <dbl>
#>  1 AL     South       3624   41.3
#>  2 AK     West        6315   66.7
#>  3 AZ     West        4530   58.1
#>  4 AR     South       3378   39.9
#>  5 CA     West        5114   62.6
#>  6 CO     West        4884   63.9
#>  7 CT     Northeast   5348   56  
#>  8 DE     South       4809   54.6
#>  9 FL     South       4815   52.6
#> 10 GA     South       4091   40.6
#> # … with 40 more rows

## version 2: join using two keys so no redundant column
df_multikey_join <- df_1 %>%
    left_join(df_2, by = c("stabbr", "region"))

df_multikey_join
#> # A tibble: 50 x 4
#>    stabbr region    income hsgrad
#>    <chr>  <fct>      <dbl>  <dbl>
#>  1 AL     South       3624   41.3
#>  2 AK     West        6315   66.7
#>  3 AZ     West        4530   58.1
#>  4 AR     South       3378   39.9
#>  5 CA     West        5114   62.6
#>  6 CO     West        4884   63.9
#>  7 CT     Northeast   5348   56  
#>  8 DE     South       4809   54.6
#>  9 FL     South       4815   52.6
#> 10 GA     South       4091   40.6
#> # … with 40 more rows
```

<sup>Created on 2020-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by nszekeres** [comment] 2020-06-15 02:49
Hi, thanks @btskinner - appreciate the 2 examples.

**Comment by btskinner** [comment] 2021-12-27 16:04
Closing since answered

**Closed by btskinner** 2021-12-27 16:04 UTC
Labels: Subject: R/Markdown/RStudio, Subject: Materials/website, Question
